# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.24 on 2020-05-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadmin', '0010_auto_20200305_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotice',
            name='is_for_task',
            field=models.BooleanField(default=False, verbose_name='是否为任务通知模板'),
        ),
        migrations.AlterField(
            model_name='customnotice',
            name='action',
            field=models.CharField(
                choices=[
                    ('TERMINATE', '单据终止通知'),
                    ('FOLLOW', '邀请关注通知'),
                    ('INVITE', '邀请评价通知'),
                    ('SUPERVISE', '单据督办通知'),
                    ('SUSPEND', '单据挂起通知'),
                    ('UNSUSPEND', '单据恢复通知'),
                    ('TRANSITION', '单据待办通知'),
                    ('WAITING_FOR_OPERATE', '任务待办通知'),
                    ('WAITING_FOR_CONFIRM', '任务待总结通知'),
                    ('FINISHED', '单据结束通知'),
                ],
                default='default',
                max_length=32,
                verbose_name='通知模板类型',
            ),
        ),
    ]
