# Generated by Django 3.2.4 on 2022-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iadmin", "0015_auto_20210318_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="customnotice",
            name="project_key",
            field=models.CharField(
                default="public", max_length=32, verbose_name="项目key"
            ),
        ),
    ]
