# Generated by Django 3.2.4 on 2022-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iadmin', '0016_customnotice_project_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnotice',
            name='notify_type',
            field=models.CharField(default='EMAIL', max_length=32, verbose_name='通知方式'),
        ),
    ]
