# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pipeline.django_signal_valve.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0021_delete_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_path', models.TextField(verbose_name='信号模块名')),
                ('name', models.CharField(max_length=64, verbose_name='信号属性名')),
                ('kwargs', pipeline.django_signal_valve.models.IOField(verbose_name='信号参数')),
            ],
        ),
        migrations.AlterField(
            model_name='pipelineinstance',
            name='execution_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_snapshot_instances', to='pipeline.Snapshot', verbose_name='用于实例执行的结构数据'),
        ),
        migrations.AlterField(
            model_name='pipelineinstance',
            name='name',
            field=models.CharField(default='default_instance', max_length=128, verbose_name='实例名称'),
        ),
        migrations.AlterField(
            model_name='pipelineinstance',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_instances', to='pipeline.Snapshot', verbose_name='实例结构数据，指向实例对应的模板的结构数据'),
        ),
        migrations.AlterField(
            model_name='pipelineinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.PipelineTemplate', verbose_name='Pipeline模板'),
        ),
        migrations.AlterField(
            model_name='pipelineinstance',
            name='tree_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_info_instances', to='pipeline.TreeInfo', verbose_name='提前计算好的一些流程结构数据'),
        ),
        migrations.AlterField(
            model_name='pipelinetemplate',
            name='name',
            field=models.CharField(default='default_template', max_length=128, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='pipelinetemplate',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='snapshot_templates', to='pipeline.Snapshot', verbose_name='模板结构数据'),
        ),
    ]
