# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0022_auto_20191101_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineinstance',
            name='is_revoked',
            field=models.BooleanField(default=False, verbose_name='是否已经撤销'),
        ),
    ]
