# Generated by Django 3.2.4 on 2021-06-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0023_pipelineinstance_is_revoked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineinstance',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.snapshot', verbose_name='模板数据 ID'),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipelinetemplate', verbose_name='模板 ID'),
        ),
    ]
