# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20181228_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loopactivityhistory',
            name='data',
        ),
        migrations.RemoveField(
            model_name='loopactivityhistory',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='LoopActivityStatus',
        ),
        migrations.AddField(
            model_name='pipelinemodel',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='流程优先级'),
        ),
        migrations.AlterField(
            model_name='functionswitch',
            name='description',
            field=models.TextField(default='', verbose_name='功能描述'),
        ),
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.HistoryData'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nodecelerytask',
            name='celery_task_id',
            field=models.CharField(default='', max_length=40, verbose_name='celery 任务 ID'),
        ),
        migrations.AlterField(
            model_name='nodecelerytask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noderelationship',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='current_node_id',
            field=models.CharField(db_index=True, default='', max_length=32, verbose_name='当前推进到的节点的 ID'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='destination_id',
            field=models.CharField(default='', max_length=32, verbose_name='遇到该 ID 的节点就停止推进'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='parent_id',
            field=models.CharField(default='', max_length=32, verbose_name='父 process 的 ID'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.ProcessSnapshot'),
        ),
        migrations.AlterField(
            model_name='processcelerytask',
            name='celery_task_id',
            field=models.CharField(default='', max_length=40, verbose_name='celery 任务 ID'),
        ),
        migrations.AlterField(
            model_name='processcelerytask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processsnapshot',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedulecelerytask',
            name='celery_task_id',
            field=models.CharField(default='', max_length=40, verbose_name='celery 任务 ID'),
        ),
        migrations.AlterField(
            model_name='schedulecelerytask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='subprocessrelationship',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='LoopActivityHistory',
        ),
        migrations.DeleteModel(
            name='LoopActivityScheduleHistory',
        ),
    ]
