# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20191101_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleservice',
            name='multi_callback_enabled',
            field=models.BooleanField(default=False, verbose_name='是否支持多次回调'),
        ),
    ]
