# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import pipeline.engine.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_scheduleservice_multi_callback_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiCallbackData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('schedule_id', models.CharField(max_length=64, verbose_name='回调服务ID')),
                ('data', pipeline.engine.models.fields.IOField(verbose_name='回调数据')),
            ],
        ),
        migrations.CreateModel(
            name='SendFailedCeleryTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='任务名')),
                ('kwargs', models.TextField(verbose_name='任务参数')),
                ('type', models.IntegerField(choices=[(0, 'empty'), (1, 'process'), (2, 'node'), (3, 'schedule')], verbose_name='任务类型')),
                ('extra_kwargs', models.TextField(verbose_name='额外参数')),
                ('exec_trace', models.TextField(verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='pipelinemodel',
            name='queue',
            field=models.CharField(default='', max_length=512, verbose_name='流程使用的队列名'),
        ),
        migrations.AddField(
            model_name='status',
            name='state_refresh_at',
            field=models.DateTimeField(null=True, verbose_name='上次状态更新的时间'),
        ),
        migrations.AlterField(
            model_name='data',
            name='ex_data',
            field=pipeline.engine.models.fields.IOField(default=None, verbose_name='异常数据'),
        ),
        migrations.AlterField(
            model_name='data',
            name='inputs',
            field=pipeline.engine.models.fields.IOField(default=None, verbose_name='输入数据'),
        ),
        migrations.AlterField(
            model_name='data',
            name='outputs',
            field=pipeline.engine.models.fields.IOField(default=None, verbose_name='输出数据'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='ex_data',
            field=pipeline.engine.models.fields.IOField(default=None, verbose_name='异常数据'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='inputs',
            field=pipeline.engine.models.fields.IOField(default=None, verbose_name='输入数据'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='outputs',
            field=pipeline.engine.models.fields.IOField(default=None, verbose_name='输出数据'),
        ),
        migrations.AlterField(
            model_name='noderelationship',
            name='distance',
            field=models.IntegerField(db_index=True, verbose_name='距离'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='is_alive',
            field=models.BooleanField(db_index=True, default=True, verbose_name='该 process 是否还有效'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='is_frozen',
            field=models.BooleanField(db_index=True, default=False, verbose_name='该 process 是否被冻结'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='is_sleep',
            field=models.BooleanField(db_index=True, default=False, verbose_name='该 process 是否正在休眠'),
        ),
        migrations.AlterField(
            model_name='pipelineprocess',
            name='root_pipeline_id',
            field=models.CharField(db_index=True, max_length=32, verbose_name='根 pipeline 的 ID'),
        ),
        migrations.AlterField(
            model_name='scheduleservice',
            name='is_scheduling',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否正在被调度'),
        ),
    ]
