# Generated by Django 4.2.26 on 2025-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_auto_20200722_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleservice',
            name='last_schedule_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后调度时间'),
        ),
    ]
