app_code: bk_itsm
app_name: 流程服务
app_name_en: ITSM
author: 蓝鲸智云
category: 办公应用
introduction: 流程服务是蓝鲸推出的轻量级ITSM，通过可自定义设计的流程模块，覆盖IT服务中的不同管理活动或应用场景。帮助企业用户规范内部管理流程，提升沟通及管理效率。
introduction_en: bk_itsm is a lightweight ITSM created by Blueking. It covers different application scenarios in IT services through customizable workflows and help enterprise users to implement standardize IT workflow, improve communication and management efficiency.
version: 2.6.5
language: python
is_use_celery: True
is_use_celery_with_gevent: False
language_support: 英语
container:
    memory: 4096
desktop:
    width: 1200
    height: 720
    is_max: True
    open_mode: new_tab
date: 2020-07-02 18:00:00
env:
  - key: BKAPP_ENABLE_SHARED_FS
    value: True

