# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

CREATE_SERVICE_DATA = {
    "name": "测试服务",
    "desc": "测试服务",
    "key": "request",
    "catalog_id": 2,
    "project_key": "0",
}

CONFIGS = {
    "workflow_config": {
        "is_auto_approve": False,
        "is_revocable": True,
        "revoke_config": {"type": 2, "state": 0},
        "is_supervise_needed": False,
        "supervise_type": "EMPTY",
        "supervisor": "",
        "notify": [],
        "notify_rule": "NONE",
        "notify_freq": 0,
    },
    "display_type": "OPEN",
    "can_ticket_agency": False,
}

IMPORT_SERVICE_DATA = {
    "key": "request",
    "name": "测试导入",
    "desc": "测试导入",
    "workflow": {
        "is_deleted": False,
        "name": "测试导入",
        "desc": "",
        "flow_type": "other",
        "is_enabled": True,
        "is_revocable": True,
        "revoke_config": {"type": 2, "state": 0},
        "is_draft": False,
        "is_builtin": False,
        "is_task_needed": False,
        "owners": "",
        "notify_rule": "ONCE",
        "notify_freq": 0,
        "is_biz_needed": False,
        "is_auto_approve": False,
        "is_iam_used": True,
        "is_supervise_needed": False,
        "supervise_type": "EMPTY",
        "supervisor": "",
        "engine_version": "PIPELINE_V1",
        "version_number": "20220308191107",
        "table": {
            "id": 7,
            "is_deleted": False,
            "name": "\u7b80\u5355\u6a21\u578b_20211210160940",
            "desc": "2\u4e2a\u5b57\u6bb5",
            "version": "EMPTY",
            "fields": [
                {
                    "id": 1,
                    "is_deleted": False,
                    "is_builtin": True,
                    "is_readonly": False,
                    "is_valid": True,
                    "display": True,
                    "source_type": "CUSTOM",
                    "source_uri": "",
                    "api_instance_id": 0,
                    "kv_relation": {},
                    "type": "STRING",
                    "key": "title",
                    "name": "\u6807\u9898",
                    "layout": "COL_12",
                    "validate_type": "REQUIRE",
                    "show_type": 1,
                    "show_conditions": {},
                    "regex": "EMPTY",
                    "regex_config": {},
                    "custom_regex": "",
                    "desc": "\u8bf7\u8f93\u5165\u6807\u9898",
                    "tips": "",
                    "is_tips": False,
                    "default": "",
                    "choice": [],
                    "related_fields": {},
                    "meta": {},
                    "flow_type": "DEFAULT",
                    "project_key": "public",
                    "source": "BASE-MODEL",
                },
                {
                    "id": 5,
                    "is_deleted": False,
                    "is_builtin": True,
                    "is_readonly": False,
                    "is_valid": True,
                    "display": True,
                    "source_type": "RPC",
                    "source_uri": "ticket_status",
                    "api_instance_id": 0,
                    "kv_relation": {},
                    "type": "SELECT",
                    "key": "current_status",
                    "name": "\u5de5\u5355\u72b6\u6001",
                    "layout": "COL_12",
                    "validate_type": "REQUIRE",
                    "show_type": 1,
                    "show_conditions": {},
                    "regex": "EMPTY",
                    "regex_config": {},
                    "custom_regex": "",
                    "desc": "\u8bf7\u9009\u62e9\u5de5\u5355\u72b6\u6001",
                    "tips": "",
                    "is_tips": False,
                    "default": "",
                    "choice": [],
                    "related_fields": {},
                    "meta": {},
                    "flow_type": "DEFAULT",
                    "project_key": "public",
                    "source": "BASE-MODEL",
                },
            ],
            "fields_order": [1, 5],
            "field_key_order": ["title", "current_status"],
        },
        "creator": "",
        "updated_by": "",
        "workflow_id": 4,
        "version_message": "",
        "states": {
            "17": {
                "workflow": 4,
                "id": 17,
                "key": 17,
                "name": "\u5f00\u59cb",
                "desc": "",
                "distribute_type": "PROCESS",
                "axis": {"x": 150, "y": 150},
                "is_builtin": True,
                "variables": {"inputs": [], "outputs": []},
                "tag": "DEFAULT",
                "processors_type": "OPEN",
                "processors": "",
                "assignors": "",
                "assignors_type": "EMPTY",
                "delivers": "",
                "delivers_type": "EMPTY",
                "can_deliver": False,
                "extras": {},
                "is_draft": False,
                "is_terminable": False,
                "fields": [],
                "type": "START",
                "api_instance_id": 0,
                "is_sequential": False,
                "finish_condition": {},
                "is_multi": False,
                "is_allow_skip": False,
                "creator": None,
                "create_at": "2021-12-10 16:09:40",
                "updated_by": None,
                "update_at": "2021-12-10 16:09:41",
                "end_at": None,
                "is_first_state": False,
            },
            "18": {
                "workflow": 4,
                "id": 18,
                "key": 18,
                "name": "\u63d0\u5355",
                "desc": "",
                "distribute_type": "PROCESS",
                "axis": {"x": 285, "y": 150},
                "is_builtin": True,
                "variables": {"inputs": [], "outputs": []},
                "tag": "DEFAULT",
                "processors_type": "OPEN",
                "processors": "",
                "assignors": "",
                "assignors_type": "EMPTY",
                "delivers": "",
                "delivers_type": "EMPTY",
                "can_deliver": False,
                "extras": {"ticket_status": {"name": "", "type": "keep"}},
                "is_draft": False,
                "is_terminable": False,
                "fields": [37, 38, 39, 40, 41],
                "type": "NORMAL",
                "api_instance_id": 0,
                "is_sequential": False,
                "finish_condition": {},
                "is_multi": False,
                "is_allow_skip": False,
                "creator": None,
                "create_at": "2021-12-10 16:09:40",
                "updated_by": "admin",
                "update_at": "2022-03-03 19:05:50",
                "end_at": None,
                "is_first_state": True,
            },
            "19": {
                "workflow": 4,
                "id": 19,
                "key": 19,
                "name": "\u7ed3\u675f",
                "desc": "",
                "distribute_type": "PROCESS",
                "axis": {"x": 880, "y": 150},
                "is_builtin": True,
                "variables": {"inputs": [], "outputs": []},
                "tag": "DEFAULT",
                "processors_type": "OPEN",
                "processors": "",
                "assignors": "",
                "assignors_type": "EMPTY",
                "delivers": "",
                "delivers_type": "EMPTY",
                "can_deliver": False,
                "extras": {},
                "is_draft": False,
                "is_terminable": False,
                "fields": [],
                "type": "END",
                "api_instance_id": 0,
                "is_sequential": False,
                "finish_condition": {},
                "is_multi": False,
                "is_allow_skip": False,
                "creator": None,
                "create_at": "2021-12-10 16:09:40",
                "updated_by": None,
                "update_at": "2021-12-10 16:09:41",
                "end_at": None,
                "is_first_state": False,
            },
            "20": {
                "workflow": 4,
                "id": 20,
                "key": 20,
                "name": "\u8d85\u7ea7\u7ba1\u7406\u5458\u5ba1\u6279",
                "desc": "",
                "distribute_type": "PROCESS",
                "axis": {"x": 540, "y": 150},
                "is_builtin": False,
                "variables": {
                    "inputs": [],
                    "outputs": [
                        {
                            "source": "global",
                            "state": 474,
                            "type": "STRING",
                            "key": "d8f97aac22716f21d133e9ce44246ddb",
                            "name": "\u5ba1\u6279\u7ed3\u679c",
                            "meta": {
                                "code": "NODE_APPROVE_RESULT",
                                "type": "SELECT",
                                "choice": [
                                    {"key": "False", "name": "\u62d2\u7edd"},
                                    {"key": "True", "name": "\u901a\u8fc7"},
                                ],
                            },
                        }
                    ],
                },
                "tag": "DEFAULT",
                "processors_type": "IAM",
                "processors": "13",
                "assignors": "",
                "assignors_type": "EMPTY",
                "delivers": "",
                "delivers_type": "EMPTY",
                "can_deliver": False,
                "extras": {"ticket_status": {"name": "", "type": "keep"}},
                "is_draft": False,
                "is_terminable": False,
                "fields": [42, 43, 44],
                "type": "APPROVAL",
                "api_instance_id": 0,
                "is_sequential": False,
                "finish_condition": {},
                "is_multi": False,
                "is_allow_skip": False,
                "creator": None,
                "create_at": "2021-12-10 16:09:40",
                "updated_by": None,
                "update_at": "2021-12-10 16:09:41",
                "end_at": None,
                "is_first_state": False,
            },
        },
        "transitions": {
            "16": {
                "workflow": 4,
                "id": 16,
                "from_state": 17,
                "to_state": 18,
                "name": "",
                "axis": {"start": "Right", "end": "Left"},
                "condition": {
                    "expressions": [
                        {
                            "type": "and",
                            "expressions": [
                                {"key": "G_INT_1", "condition": "==", "value": 1}
                            ],
                        }
                    ],
                    "type": "and",
                },
                "condition_type": "default",
                "creator": None,
                "create_at": "2021-12-10 16:09:41",
                "updated_by": None,
                "update_at": "2021-12-10 16:09:41",
                "end_at": None,
            },
            "17": {
                "workflow": 4,
                "id": 17,
                "from_state": 18,
                "to_state": 20,
                "name": "\u9ed8\u8ba4",
                "axis": {"start": "Right", "end": "Left"},
                "condition": {
                    "expressions": [
                        {
                            "type": "and",
                            "expressions": [
                                {"key": "G_INT_1", "condition": "==", "value": 1}
                            ],
                        }
                    ],
                    "type": "and",
                },
                "condition_type": "default",
                "creator": None,
                "create_at": "2021-12-10 16:09:41",
                "updated_by": None,
                "update_at": "2021-12-10 16:09:41",
                "end_at": None,
            },
            "18": {
                "workflow": 4,
                "id": 18,
                "from_state": 20,
                "to_state": 19,
                "name": "\u9ed8\u8ba4",
                "axis": {"start": "Right", "end": "Left"},
                "condition": {
                    "expressions": [
                        {
                            "type": "and",
                            "expressions": [
                                {"key": "G_INT_1", "condition": "==", "value": 1}
                            ],
                        }
                    ],
                    "type": "and",
                },
                "condition_type": "default",
                "creator": None,
                "create_at": "2021-12-10 16:09:41",
                "updated_by": None,
                "update_at": "2021-12-10 16:09:41",
                "end_at": None,
            },
        },
        "triggers": [],
        "fields": {
            "37": {
                "id": 37,
                "is_deleted": False,
                "is_builtin": True,
                "is_readonly": False,
                "is_valid": True,
                "display": True,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "STRING",
                "key": "title",
                "name": "\u6807\u9898",
                "layout": "COL_12",
                "validate_type": "REQUIRE",
                "show_type": 1,
                "show_conditions": {},
                "regex": "EMPTY",
                "regex_config": {},
                "custom_regex": "",
                "desc": "\u8bf7\u8f93\u5165\u6807\u9898",
                "tips": "",
                "is_tips": False,
                "default": "",
                "choice": [],
                "related_fields": {},
                "meta": {},
                "workflow_id": 4,
                "state_id": "",
                "source": "TABLE",
            },
            "38": {
                "id": 38,
                "is_deleted": False,
                "is_builtin": False,
                "is_readonly": False,
                "is_valid": True,
                "display": False,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "STRING",
                "key": "application_type",
                "name": "\u7533\u8bf7\u7c7b\u578b",
                "layout": "COL_12",
                "validate_type": "REQUIRE",
                "show_type": 1,
                "show_conditions": {},
                "regex": "EMPTY",
                "regex_config": {
                    "rule": {
                        "expressions": [
                            {
                                "condition": "",
                                "key": "",
                                "source": "field",
                                "type": "STRING",
                                "value": "",
                            }
                        ],
                        "type": "and",
                    }
                },
                "custom_regex": "",
                "desc": "",
                "tips": "",
                "is_tips": False,
                "default": "",
                "choice": [],
                "related_fields": {},
                "meta": {},
                "workflow_id": 4,
                "state_id": 18,
                "source": "CUSTOM",
            },
            "39": {
                "id": 39,
                "is_deleted": False,
                "is_builtin": False,
                "is_readonly": False,
                "is_valid": True,
                "display": False,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "STRING",
                "key": "reason",
                "name": "\u7533\u8bf7\u7406\u7531",
                "layout": "COL_12",
                "validate_type": "REQUIRE",
                "show_type": 1,
                "show_conditions": {},
                "regex": "EMPTY",
                "regex_config": {
                    "rule": {
                        "expressions": [
                            {
                                "condition": "",
                                "key": "",
                                "source": "field",
                                "type": "STRING",
                                "value": "",
                            }
                        ],
                        "type": "and",
                    }
                },
                "custom_regex": "",
                "desc": "",
                "tips": "",
                "is_tips": False,
                "default": "",
                "choice": [],
                "related_fields": {},
                "meta": {},
                "workflow_id": 4,
                "state_id": 18,
                "source": "CUSTOM",
            },
            "40": {
                "id": 40,
                "is_deleted": False,
                "is_builtin": False,
                "is_readonly": False,
                "is_valid": True,
                "display": False,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "STRING",
                "key": "organization",
                "name": "\u7ec4\u7ec7",
                "layout": "COL_12",
                "validate_type": "REQUIRE",
                "show_type": 1,
                "show_conditions": {},
                "regex": "EMPTY",
                "regex_config": {
                    "rule": {
                        "expressions": [
                            {
                                "condition": "",
                                "key": "",
                                "source": "field",
                                "type": "STRING",
                                "value": "",
                            }
                        ],
                        "type": "and",
                    }
                },
                "custom_regex": "",
                "desc": "",
                "tips": "",
                "is_tips": False,
                "default": "",
                "choice": [],
                "related_fields": {},
                "meta": {},
                "workflow_id": 4,
                "state_id": 18,
                "source": "CUSTOM",
            },
            "41": {
                "id": 41,
                "is_deleted": False,
                "is_builtin": False,
                "is_readonly": False,
                "is_valid": True,
                "display": False,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "CUSTOM-FORM",
                "key": "content",
                "name": "\u7533\u8bf7\u5185\u5bb9",
                "layout": "COL_12",
                "validate_type": "REQUIRE",
                "show_type": 1,
                "show_conditions": {},
                "regex": "EMPTY",
                "regex_config": {"rule": {"expressions": [], "type": "and"}},
                "custom_regex": "",
                "desc": "",
                "tips": "",
                "is_tips": False,
                "default": '{\n    "schemes": {},\n    "form_data": []\n}',
                "choice": [],
                "related_fields": {},
                "meta": {},
                "workflow_id": 4,
                "state_id": 18,
                "source": "CUSTOM",
            },
            "42": {
                "id": 42,
                "is_deleted": False,
                "is_builtin": False,
                "is_readonly": False,
                "is_valid": True,
                "display": True,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "RADIO",
                "key": "b48d699d8ebb63db91cd68837ae32509",
                "name": "\u5ba1\u6279\u610f\u89c1",
                "layout": "COL_6",
                "validate_type": "REQUIRE",
                "show_type": 1,
                "show_conditions": {},
                "regex": "EMPTY",
                "regex_config": {},
                "custom_regex": "",
                "desc": "",
                "tips": "",
                "is_tips": False,
                "default": "True",
                "choice": [
                    {"key": "True", "name": "\u901a\u8fc7"},
                    {"key": "False", "name": "\u62d2\u7edd"},
                ],
                "related_fields": {},
                "meta": {"code": "APPROVE_RESULT"},
                "workflow_id": 4,
                "state_id": 20,
                "source": "CUSTOM",
            },
            "43": {
                "id": 43,
                "is_deleted": False,
                "is_builtin": False,
                "is_readonly": False,
                "is_valid": True,
                "display": False,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "TEXT",
                "key": "301ae3fb3123aaa2d28704fc83c86e45",
                "name": "\u5907\u6ce8",
                "layout": "COL_12",
                "validate_type": "OPTION",
                "show_type": 0,
                "show_conditions": {
                    "expressions": [
                        {
                            "value": "False",
                            "type": "RADIO",
                            "condition": "==",
                            "key": "b48d699d8ebb63db91cd68837ae32509",
                        }
                    ],
                    "type": "and",
                },
                "regex": "EMPTY",
                "regex_config": {},
                "custom_regex": "",
                "desc": "",
                "tips": "",
                "is_tips": False,
                "default": "",
                "choice": [],
                "related_fields": {},
                "meta": {},
                "workflow_id": 4,
                "state_id": 20,
                "source": "CUSTOM",
            },
            "44": {
                "id": 44,
                "is_deleted": False,
                "is_builtin": False,
                "is_readonly": False,
                "is_valid": True,
                "display": False,
                "source_type": "CUSTOM",
                "source_uri": "",
                "api_instance_id": 0,
                "kv_relation": {},
                "type": "TEXT",
                "key": "bc4a4f1762f80e8a5800118f8c7a833b",
                "name": "\u5907\u6ce8",
                "layout": "COL_12",
                "validate_type": "REQUIRE",
                "show_type": 0,
                "show_conditions": {
                    "expressions": [
                        {
                            "value": "True",
                            "type": "RADIO",
                            "condition": "==",
                            "key": "b48d699d8ebb63db91cd68837ae32509",
                        }
                    ],
                    "type": "and",
                },
                "regex": "EMPTY",
                "regex_config": {},
                "custom_regex": "",
                "desc": "",
                "tips": "",
                "is_tips": False,
                "default": "",
                "choice": [],
                "related_fields": {},
                "meta": {},
                "workflow_id": 4,
                "state_id": 20,
                "source": "CUSTOM",
            },
        },
        "notify": [1, 2],
        "extras": {},
    },
    "owners": "admin",
    "can_ticket_agency": False,
    "is_valid": True,
    "display_type": "API",
    "display_role": ",BK_IAM,",
    "source": "custom",
    "project_key": "0",
}
