# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.24 on 2019-11-14 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_state_tag'),
    ]

    operations = [
        migrations.AlterModelManagers(name='table', managers=[],),
        migrations.RemoveField(model_name='table', name='service_type',),
        migrations.AddField(
            model_name='field',
            name='source',
            field=models.CharField(
                choices=[('CUSTOM', '自定义添加'), ('TABLE', '基础模型添加')], default='CUSTOM', max_length=32, verbose_name='添加方式'
            ),
        ),
        migrations.AddField(
            model_name='state',
            name='read_only_fields',
            field=jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='只读表单字段(ID列表，按顺序排列)'),
        ),
        migrations.AddField(
            model_name='table', name='fields_order', field=jsonfield.fields.JSONField(default=[], verbose_name='字段排序'),
        ),
        migrations.AddField(
            model_name='table', name='is_builtin', field=models.BooleanField(default=False, verbose_name='是否内置字段'),
        ),
        migrations.AddField(
            model_name='table',
            name='version',
            field=models.CharField(blank=True, default='EMPTY', max_length=64, null=True, verbose_name='Table版本：空'),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='table',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='基础模型快照字典'),
        ),
        migrations.AlterField(
            model_name='defaultfield',
            name='source_type',
            field=models.CharField(
                choices=[('CUSTOM', '自定义数据'), ('API', '接口数据'), ('DATADICT', '数据字典'), ('RPC', 'RPC数据')],
                default='CUSTOM',
                max_length=32,
                verbose_name='数据来源类型',
            ),
        ),
        migrations.AlterField(
            model_name='field',
            name='source_type',
            field=models.CharField(
                choices=[('CUSTOM', '自定义数据'), ('API', '接口数据'), ('DATADICT', '数据字典'), ('RPC', 'RPC数据')],
                default='CUSTOM',
                max_length=32,
                verbose_name='数据来源类型',
            ),
        ),
        migrations.AlterField(
            model_name='table',
            name='fields',
            field=models.ManyToManyField(help_text='关联的公共字段', related_name='tables', to='workflow.TemplateField'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='source_type',
            field=models.CharField(
                choices=[('CUSTOM', '自定义数据'), ('API', '接口数据'), ('DATADICT', '数据字典'), ('RPC', 'RPC数据')],
                default='CUSTOM',
                max_length=32,
                verbose_name='数据来源类型',
            ),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='table',
            field=models.ForeignKey(
                blank=True,
                help_text='关联的基础模型',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='used_workflow',
                to='workflow.Table',
            ),
        ),
    ]
