# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.24 on 2020-02-07 16:46
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20200114_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('component_key', models.CharField(max_length=64, verbose_name='原子key')),
                ('type', models.CharField(choices=[('state_button', '节点按钮')], max_length=32, verbose_name='类型')),
                ('condition', jsonfield.fields.JSONCharField(default={}, max_length=255, verbose_name='触发条件')),
                ('inputs', jsonfield.fields.JSONCharField(default={}, max_length=255, verbose_name='传入参数')),
                ('state_id', models.IntegerField(blank=True, null=True, verbose_name='节点ID')),
                ('workflow_id', models.IntegerField(blank=True, null=True, verbose_name='流程ID')),
            ],
            options={'verbose_name': '触发器', 'verbose_name_plural': '触发器',},
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='triggers',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='触发器快照字典'),
        ),
    ]
