# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-10-02 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0043_auto_20210906_1448"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="workflow",
        #     name="is_auto_approve",
        #     field=models.BooleanField(default=False, verbose_name="是否自动过单"),
        # ),
        # migrations.AddField(
        #     model_name="workflowversion",
        #     name="is_auto_approve",
        #     field=models.BooleanField(default=False, verbose_name="是否自动过单"),
        # ),
    ]
