# Generated by Django 3.2.4 on 2021-12-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0045_state_is_allow_skip"),
        ("workflow", "0048_alter_state_type"),
    ]

    operations = []
