# Generated by Django 3.2.4 on 2022-04-06 17:48

from django.db import migrations, models
from django.db.models import NOT_PROVIDED

from itsm.workflow.models import State, Workflow, WorkflowVersion


class AlterField(migrations.AlterField):
    """兼容性措施"""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if self.allow_migrate_model(schema_editor.connection.alias, to_model):
            from_model = from_state.apps.get_model(app_label, self.model_name)
            if self.name == "is_allow_skip":
                from_field = State.is_allow_skip.field
            elif self.name == "is_auto_approve" and self.model_name == "workflow":
                from_field = Workflow.is_auto_approve.field
            elif (
                self.name == "is_auto_approve" and self.model_name == "workflowversion"
            ):
                from_field = WorkflowVersion.is_auto_approve.field
            else:
                from_field = from_model._meta.get_field(self.name)
            to_field = to_model._meta.get_field(self.name)
            if not self.preserve_default:
                to_field.default = self.field.default
            schema_editor.alter_field(from_model, from_field, to_field)
            if not self.preserve_default:
                to_field.default = NOT_PROVIDED


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0049_merge_0045_state_is_allow_skip_0048_alter_state_type"),
    ]

    operations = [
        AlterField(
            model_name="state",
            name="is_allow_skip",
            field=models.BooleanField(default=False, verbose_name="是否允许在单据处理人为空时跳过"),
        ),
        AlterField(
            model_name="workflow",
            name="is_auto_approve",
            field=models.BooleanField(default=False, verbose_name="是否自动过单"),
        ),
        AlterField(
            model_name="workflowversion",
            name="is_auto_approve",
            field=models.BooleanField(default=False, verbose_name="是否自动过单"),
        ),
        AlterField(
            model_name="state",
            name="type",
            field=models.CharField(
                choices=[
                    ("START", "开始节点(圆形)"),
                    ("NORMAL", "普通节点"),
                    ("SIGN", "会签节点"),
                    ("APPROVAL", "审批节点"),
                    ("TASK", "自动节点"),
                    ("TASK-SOPS", "标准运维节点"),
                    ("TASK-DEVOPS", "蓝盾任务节点"),
                    ("WEBHOOK", "WebHook节点"),
                    ("ROUTER", "分支网关节点(菱形)"),
                    ("ROUTER-P", "并行网关节点"),
                    ("COVERAGE", "汇聚网关节点"),
                    ("END", "结束节点(圆形)"),
                ],
                default="NORMAL",
                max_length=32,
                verbose_name="状态类型",
            ),
        ),
    ]
