# Generated by Django 3.2.25 on 2024-11-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0010_auto_20210621_1206'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='remoteapi',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='remoteapiinstance',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='remotesystem',
            managers=[
            ],
        ),
    ]
