# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.24 on 2020-04-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200413_1756'),
    ]

    operations = [
        migrations.AlterModelManagers(name='task', managers=[],),
        migrations.RemoveField(model_name='task', name='fields',),
        migrations.AddField(
            model_name='task',
            name='activity_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Pipeline节点ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='processors',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='处理人列表'),
        ),
        migrations.AddField(
            model_name='task',
            name='processors_type',
            field=models.CharField(
                choices=[
                    ('CMDB', 'CMDB业务公用角色'),
                    ('GENERAL', '通用角色表'),
                    ('OPEN', '不限'),
                    ('PERSON', '个人'),
                    ('STARTER', '提单人'),
                    ('BY_ASSIGNOR', '派单人指定'),
                    ('EMPTY', '无'),
                    ('ORGANIZATION', '组织架构'),
                    ('VARIABLE', '引用变量'),
                ],
                default='EMPTY',
                max_length=32,
                verbose_name='处理人类型',
            ),
        ),
        migrations.AddField(
            model_name='taskfield', name='_value', field=models.TextField(blank=True, null=True, verbose_name='表单值'),
        ),
        migrations.AddField(
            model_name='taskfield', name='sequence', field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='task', name='name', field=models.CharField(max_length=255, verbose_name='任务的名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('NEW', '新建'),
                    ('WAITING_FOR_OPERATE', '待执行'),
                    ('RUNNING', '执行中'),
                    ('WAITING_FOR_CONFIRM', '待总结'),
                    ('FINISHED', '完成'),
                ],
                default='NEW',
                max_length=64,
                verbose_name='任务的状态',
            ),
        ),
    ]
