# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.23 on 2020-12-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_task_execute_state_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(max_length=64, verbose_name='修改人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('ticket_id', models.IntegerField(verbose_name='单据ID')),
                ('project_id', models.CharField(default='', max_length=64, verbose_name='项目ID/业务ID')),
                ('task_id', models.CharField(max_length=64, verbose_name='itsm任务ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='任务的名称')),
                ('sub_pipeline_id', models.IntegerField(verbose_name='子流水线ID')),
                ('sub_task_id', models.IntegerField(blank=True, null=True, verbose_name='子ID，成功启动后填充')),
                ('sub_task_info', jsonfield.fields.JSONField(default={}, verbose_name='子任务信息')),
                ('sub_task_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='子任务详情链接')),
                ('creator', models.CharField(blank=True, max_length=64, verbose_name='创建者')),
                ('executor', models.CharField(blank=True, max_length=64, verbose_name='执行者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('elapsed_time', models.IntegerField(default=0, verbose_name='当前耗时')),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('NOT_CREATED', '未创建'),
                            ('CREATE_FAILED', '创建失败'),
                            ('CREATED', '创建成功'),
                            ('START_FAILED', '启动失败'),
                            ('RUNNING', '执行中'),
                            ('FAILED', '执行失败'),
                            ('FINISHED', '执行结束'),
                            ('REVOKED', '被撤销'),
                            ('SUSPENDED', '被挂起'),
                            ('DELETED', '被删除'),
                        ],
                        default='NOT_CREATED',
                        max_length=64,
                        verbose_name='任务状态',
                    ),
                ),
            ],
            options={'verbose_name': '子任务', 'verbose_name_plural': '子任务', 'ordering': ('-id',),},
            managers=[('_objects', django.db.models.manager.Manager()),],
        ),
        migrations.AlterField(
            model_name='task',
            name='component_type',
            field=models.CharField(
                choices=[('NORMAL', '常规'), ('SOPS', '标准运维'), ('DEVOPS', '蓝盾')], max_length=64, verbose_name='任务组件类型'
            ),
        ),
        migrations.AlterField(
            model_name='task', name='execute_state_id', field=models.IntegerField(default=0, verbose_name='执行节点ID'),
        ),
    ]
