# Generated by Django 3.2.25 on 2024-11-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_auto_20210226_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='processors_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='处理人类型'),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='source_type',
            field=models.CharField(choices=[('CUSTOM', '自定义数据'), ('API', '接口数据'), ('DATADICT', '数据字典'), ('RPC', '系统数据'), ('CUSTOM_API', '自定义API')], default='CUSTOM', max_length=32, verbose_name='数据来源类型'),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='type',
            field=models.CharField(choices=[('STRING', '单行文本'), ('TEXT', '多行文本'), ('INT', '数字'), ('DATE', '日期'), ('DATETIME', '日期时间'), ('DATETIMERANGE', '时间间隔'), ('TABLE', '表格'), ('SELECT', '单选下拉框'), ('INPUTSELECT', '可输入单选下拉框'), ('MULTISELECT', '多选下拉框'), ('CHECKBOX', '复选框'), ('RADIO', '单选框'), ('MEMBER', '单个人员选择'), ('MEMBERS', '多个人员选择'), ('RICHTEXT', '富文本'), ('FILE', '附件上传'), ('CUSTOMTABLE', '自定义表格'), ('TREESELECT', '树形选择'), ('LINK', '链接'), ('CUSTOM-FORM', '自定义表单'), ('CASCADE', '级联')], default='STRING', max_length=32, verbose_name='字段类型'),
        ),
    ]
