{
 "title": "ITSM",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": "stats_counts.*" },
   { "name": "mod", "query": "stats_counts.*$app.*" },
   { "name": "sub_mod", "query": "stats_counts.*$app.$mod.*" },
   {
    "name": "task",
    "query": "stats_counts.$app.$mod.$sub_mod.tasks.*"
   }
  ]
 },
 "panels": [
  {
   "title": "任务数",
   "type": "graph",
   "description": "监测系统单据任务量",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats_counts.celery.$mod.$sub_mod.tasks.$task.succeeded, 5, 6)"
    },
    {
     "target": "aliasByNode(stats_counts.celery.$mod.$sub_mod.tasks.$task.failed, 5, 6)"
    }
   ]
  },
  {
   "title": "任务耗时",
   "type": "graph",
   "description": "监测任务耗时",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "耗时" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$app.$mod.$sub_mod.tasks.$task.runtime.upper, 6, 8)"
    }
   ]
  },
  {
   "title": "Worker心跳",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats_counts.celery.workers.*.heartbeat, 3), 'celery', 'celery@')"
    }
   ]
  },
  {
   "title": "Worker处理的任务数",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats.gauges.celery.workers.*.processed, 4), 'celery', 'celery@')"
    }
   ]
  },
  {
   "title": "Worker处理的任务数（失败）",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(stats.gauges.celery.workers.*.processed_failed, 4), 'celery', 'celery@')"
    }
   ]
  },
  {
   "title": "总任务",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.$app.*.*.*.*.succeeded), 'Total Done')"
    },
    {
     "target": "alias(sumSeries(stats_counts.$app.*.*.*.*.failed), 'Total Failure')"
    }
   ]
  },
  {
   "title": "成功",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 14 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.$app.*.*.*.*.succeeded), '成功')"
    }
   ]
  },
  {
   "title": "失败",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 14 },
   "targets": [
    {
     "target": "alias(sumSeries(stats_counts.$app.*.*.*.*.failed), '失败')"
    }
   ]
  },
  {
   "title": "队列中的任务",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.celery.queues.*.tasks, 4)"
    }
   ]
  }
 ]
}