# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.24 on 2020-06-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0008_auto_20200604_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='signal',
            field=models.CharField(
                choices=[
                    ('CREATE_TICKET', '创建单据'),
                    ('CLOSE_TICKET', '关闭单据'),
                    ('TERMINATE_TICKET', '终止单据'),
                    ('SUSPEND_TICKET', '挂起单据'),
                    ('RECOVERY_TICKET', '恢复单据'),
                    ('DELETE_TICKET', '撤销单据'),
                    ('CREATE_RELATE_TICKET', '创建关联单'),
                    ('CREATE_PARENTChILD_TICKET', '创建母子单'),
                    ('DISSOLVE_PARENTChILD_TICKET', '解除母子单'),
                    ('ENTER_STATE', '进入节点'),
                    ('LEAVE_STATE', '离开节点'),
                    ('DISTRIBUTE_STATE', '分派单据'),
                    ('CLAIM_STATE', '认领单据'),
                    ('DELIVER_STATE', '转单'),
                    ('THROUGH_TRANSITION', '进入分支'),
                    ('CREATE_TASK', '创建任务之后'),
                    ('DELETE_TASK', '删除任务'),
                    ('BEFORE_START_TASK', '执行任务之前'),
                    ('AFTER_FINISH_TASK', '执行任务之后'),
                    ('AFTER_CONFIRM_TASK', '完成任务之后'),
                ],
                max_length=128,
                verbose_name='触发事件信号',
            ),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='source_table_id',
            field=models.IntegerField(default=0, verbose_name='对应的变量来源表ID'),
        ),
    ]
