# Generated by Django 3.2.4 on 2022-01-04 10:52

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectsettings_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostomTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('project_key', models.CharField(max_length=32, verbose_name='项目key')),
                ('conditions', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='筛选条件')),
                ('order', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
