# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.24 on 2019-12-13 13:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

from bulk_update.helper import bulk_update


def migrate_data(apps, schema_editor):
    """
    to_ticket_id, from_ticket_id: IntegerField -> ForeignKeyField
    """
    TicketToTicket = apps.get_model("ticket", "TicketToTicket")

    ticket_to_tickets = []
    for ticket_to_ticket in TicketToTicket.objects.all():
        ticket_to_ticket.from_ticket_id = ticket_to_ticket.deprecated_from_ticket_id
        ticket_to_ticket.to_ticket_id = ticket_to_ticket.deprecated_to_ticket_id
        ticket_to_tickets.append(ticket_to_ticket)

    return bulk_update(ticket_to_tickets, update_fields=["from_ticket_id", "to_ticket_id"])


class Migration(migrations.Migration):
    dependencies = [
        ('ticket', '0032_auto_20191125_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettoticket', old_name='from_ticket_id', new_name='deprecated_from_ticket_id',
        ),
        migrations.RenameField(
            model_name='tickettoticket', old_name='to_ticket_id', new_name='deprecated_to_ticket_id',
        ),
        migrations.AddField(
            model_name='tickettoticket',
            name='from_ticket',
            field=models.ForeignKey(
                help_text='源单据',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='from_tickettotickets',
                to='ticket.Ticket',
            ),
        ),
        migrations.AddField(
            model_name='tickettoticket',
            name='to_ticket',
            field=models.ForeignKey(
                help_text='目标单据',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='to_tickettotickets',
                to='ticket.Ticket',
            ),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(model_name='tickettoticket', name='deprecated_from_ticket_id',),
        migrations.RemoveField(model_name='tickettoticket', name='deprecated_to_ticket_id',),
        migrations.AddField(
            model_name='tickettoticket',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='tickettoticket',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否软删除'),
        ),
        migrations.AddField(
            model_name='tickettoticket',
            name='related_status',
            field=models.CharField(
                choices=[
                    ('RUNNING', '处理中'),
                    ('BIND_SUCCESS', '绑定成功'),
                    ('BIND_FAILED', '绑定失败'),
                    ('UNBIND_SUCCESS', '解绑成功'),
                    ('UNBIND_FAILED', '解绑失败'),
                ],
                default='BIND_SUCCESS',
                max_length=32,
                verbose_name='关联状态',
            ),
        ),
        migrations.AddField(
            model_name='tickettoticket',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='tickettoticket',
            name='updated_by',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人'),
        ),
    ]
