# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.24 on 2020-02-12 15:54
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0036_auto_20200114_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('status_id', models.IntegerField(verbose_name='状态ID')),
                ('order', models.IntegerField(default=-1, verbose_name='顺序')),
                (
                    'status',
                    models.CharField(
                        choices=[('WAIT', '未激活'), ('RUNNING', '执行中'), ('FINISHED', '已完成')],
                        default='WAIT',
                        max_length=32,
                        verbose_name='任务状态',
                    ),
                ),
                ('processor', models.CharField(max_length=255, verbose_name='处理人')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_passed', models.NullBooleanField(verbose_name='是否审批通过')),
            ],
            options={'verbose_name': '会签任务', 'verbose_name_plural': '会签任务', 'ordering': ('-id',),},
            managers=[('_objects', django.db.models.manager.Manager()),],
        ),
        migrations.CreateModel(
            name='TaskField',
            fields=[
                (
                    'ticketfield_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='ticket.TicketField',
                    ),
                ),
            ],
            options={'abstract': False,},
            bases=('ticket.ticketfield',),
            managers=[('_objects', django.db.models.manager.Manager()),],
        ),
        migrations.AddField(
            model_name='status', name='is_sequential', field=models.BooleanField(default=False, verbose_name='是否是串行任务'),
        ),
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.CharField(
                choices=[
                    ('START', '开始节点(圆形)'),
                    ('NORMAL', '普通节点'),
                    ('SIGN', '会签节点'),
                    ('TASK', '自动节点'),
                    ('TASK-SOPS', '标准运维节点'),
                    ('ROUTER', '分支网关节点(菱形)'),
                    ('ROUTER-P', '并行网关节点'),
                    ('COVERAGE', '汇聚网关节点'),
                    ('END', '结束节点(圆形)'),
                ],
                default='NORMAL',
                max_length=32,
                verbose_name='节点类型',
            ),
        ),
        migrations.AlterField(
            model_name='status',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('TRANSITION', '提交'),
                    ('DISTRIBUTE', '分派'),
                    ('CLAIM', '认领'),
                    ('SIGN', '会签'),
                    ('AUTOMATIC', '自动执行'),
                ],
                default='TRANSITION',
                max_length=32,
                verbose_name='节点内部操作类型',
            ),
        ),
    ]
