# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-ITSM 蓝鲸流程服务 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-ITSM 蓝鲸流程服务 is licensed under the MIT License.

License for BK-ITSM 蓝鲸流程服务:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# Generated by Django 1.11.23 on 2021-01-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0054_auto_20201216_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='修改人')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否软删除')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('first_level_id', models.IntegerField(default=-1, verbose_name='一级组织id')),
                ('first_level_name', models.CharField(default='其他', max_length=255, verbose_name='一级组织名称')),
                ('second_level_id', models.IntegerField(default=-1, verbose_name='二级组织id')),
                ('second_level_name', models.CharField(default='其他', max_length=255, verbose_name='二级组织名称')),
                ('third_level_id', models.IntegerField(default=-1, verbose_name='三级组织id')),
                ('third_level_name', models.CharField(default='其他', max_length=255, verbose_name='三级组织名称')),
                ('family', jsonfield.fields.JSONField(default={}, verbose_name='组织树')),
            ],
            options={'verbose_name': '用户组织', 'verbose_name_plural': '用户组织',},
            managers=[('_objects', django.db.models.manager.Manager()),],
        ),
        migrations.AlterIndexTogether(
            name='ticket',
            index_together=set(
                [
                    ('create_at', 'bk_biz_id', 'service_id', 'current_status', 'service_type'),
                    ('bk_biz_id', 'service_id'),
                    ('service_id', 'create_at'),
                    ('current_status', 'create_at'),
                    ('creator', 'create_at'),
                ]
            ),
        ),
        migrations.AlterIndexTogether(
            name='ticketeventlog', index_together=set([('operate_at', 'operator', 'is_deleted')]),
        ),
        migrations.AlterIndexTogether(
            name='ticketorganization', index_together=set([('create_at', 'username'), ('create_at', 'first_level_id')]),
        ),
    ]
