# Generated by Django 3.2.4 on 2021-10-24 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0062_alter_status_processors"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRemark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        default="system",
                        max_length=64,
                        null=True,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="system",
                        max_length=64,
                        null=True,
                        verbose_name="修改人",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否软删除"
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=255, unique=True, verbose_name="目录关键字"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="评论内容"
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="节点顺序")),
                (
                    "remark_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "公开评论"),
                            ("INSIDE", "内部评论"),
                            ("ROOT", "根评论"),
                        ],
                        max_length=32,
                        verbose_name="评论类型",
                    ),
                ),
                (
                    "ticket_id",
                    models.IntegerField(default=0, max_length=32, verbose_name="单据id"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ticket.ticketremark",
                        verbose_name="上级目录",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
            managers=[
                ("_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
