# Generated by Django 3.2.4 on 2021-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0063_ticketremark"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketremark",
            name="update_log",
            field=models.JSONField(default=[], verbose_name="用户评论的更新记录"),
        ),
        migrations.AddField(
            model_name="ticketremark",
            name="users",
            field=models.JSONField(default=[], verbose_name="用户@的用户列表"),
        ),
    ]
