# Generated by Django 3.2.4 on 2021-11-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0063_alter_status_type"),
        ("ticket", "0064_auto_20211104_1206"),
    ]

    operations = []
