# Generated by Django 3.2.4 on 2022-01-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0065_merge_0063_alter_status_type_0064_auto_20211104_1206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAIT", "待处理"),
                    ("RUNNING", "处理中"),
                    ("QUEUEING", "后台处理中"),
                    ("RECEIVING", "待认领"),
                    ("DISTRIBUTING", "待分派"),
                    ("TERMINATED", "被终止"),
                    ("FINISHED", "已结束"),
                    ("FAILED", "执行失败"),
                    ("SUSPEND", "被挂起"),
                ],
                db_index=True,
                default="WAIT",
                max_length=32,
                verbose_name="节点状态",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="ticket_id",
            field=models.IntegerField(db_index=True, verbose_name="单据ID"),
        ),
        migrations.AlterField(
            model_name="status",
            name="type",
            field=models.CharField(
                choices=[
                    ("START", "开始节点(圆形)"),
                    ("NORMAL", "普通节点"),
                    ("SIGN", "会签节点"),
                    ("APPROVAL", "审批节点"),
                    ("TASK", "自动节点"),
                    ("TASK-SOPS", "标准运维节点"),
                    ("TASK-DEVOPS", "蓝盾任务节点"),
                    ("ROUTER", "分支网关节点(菱形)"),
                    ("ROUTER-P", "并行网关节点"),
                    ("COVERAGE", "汇聚网关节点"),
                    ("END", "结束节点(圆形)"),
                ],
                db_index=True,
                default="NORMAL",
                max_length=32,
                verbose_name="节点类型类型",
            ),
        ),
    ]
