# Generated by Django 3.2.4 on 2022-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0066_auto_20220113_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcommentinvite',
            name='notify_type',
            field=models.CharField(default='SMS', max_length=32, verbose_name='通知方式'),
        ),
        migrations.AlterField(
            model_name='ticketfollowernotifylog',
            name='notify_type',
            field=models.CharField(default='EMAIL', max_length=32, verbose_name='通知方式'),
        ),
        migrations.AlterField(
            model_name='ticketsupervisenotifylog',
            name='notify_type',
            field=models.CharField(default='EMAIL', max_length=32, verbose_name='通知方式'),
        ),
    ]
