# Generated by Django 3.2.4 on 2022-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0066_auto_20220113_2100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcomment",
            name="source",
            field=models.CharField(
                choices=[
                    ("WEB", "蓝鲸平台"),
                    ("SMS", "短信邀请"),
                    ("SYS", "系统自评"),
                    ("API", "OPENAPI"),
                ],
                default="SYS",
                max_length=64,
                verbose_name="评价来源",
            ),
        ),
    ]
