# Generated by Django 3.2.4 on 2022-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0069_alter_status_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskfield",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM", "自定义数据"),
                    ("API", "接口数据"),
                    ("DATADICT", "数据字典"),
                    ("RPC", "系统数据"),
                    ("CUSTOM_API", "自定义API"),
                ],
                default="CUSTOM",
                max_length=32,
                verbose_name="数据来源类型",
            ),
        ),
        migrations.AlterField(
            model_name="ticketfield",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CUSTOM", "自定义数据"),
                    ("API", "接口数据"),
                    ("DATADICT", "数据字典"),
                    ("RPC", "系统数据"),
                    ("CUSTOM_API", "自定义API"),
                ],
                default="CUSTOM",
                max_length=32,
                verbose_name="数据来源类型",
            ),
        ),
    ]
