# Generated by Django 3.2.4 on 2022-08-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0070_auto_20220721_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="tag",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, null=True, verbose_name="单据标签"
            ),
        ),
    ]
