# Generated by Django 3.2.25 on 2024-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0071_ticket_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentionusers',
            name='ticket_id',
            field=models.IntegerField(db_index=True, verbose_name='单号'),
        ),
        migrations.AlterField(
            model_name='signtask',
            name='status_id',
            field=models.IntegerField(db_index=True, verbose_name='状态ID'),
        ),
        migrations.AlterField(
            model_name='ticketglobalvariable',
            name='ticket_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='关联单据'),
        ),
    ]
