# Generated by Django 3.2.25 on 2025-07-30 15:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0072_auto_20240513_1608'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticketfollowernotifylog',
            managers=[
                ('_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='assignors_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='派单人类型'),
        ),
        migrations.AlterField(
            model_name='status',
            name='delivers_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='转单人类型'),
        ),
        migrations.AlterField(
            model_name='status',
            name='processors_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='处理人类型'),
        ),
        migrations.AlterField(
            model_name='taskfield',
            name='type',
            field=models.CharField(choices=[('STRING', '单行文本'), ('TEXT', '多行文本'), ('INT', '数字'), ('DATE', '日期'), ('DATETIME', '日期时间'), ('DATETIMERANGE', '时间间隔'), ('TABLE', '表格'), ('SELECT', '单选下拉框'), ('INPUTSELECT', '可输入单选下拉框'), ('MULTISELECT', '多选下拉框'), ('CHECKBOX', '复选框'), ('RADIO', '单选框'), ('MEMBER', '单个人员选择'), ('MEMBERS', '多个人员选择'), ('RICHTEXT', '富文本'), ('FILE', '附件上传'), ('CUSTOMTABLE', '自定义表格'), ('TREESELECT', '树形选择'), ('LINK', '链接'), ('CUSTOM-FORM', '自定义表单'), ('CASCADE', '级联')], default='STRING', max_length=32, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='current_assignor_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='分派人类型'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='current_processors_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='处理者类型'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='current_status',
            field=models.CharField(db_index=True, max_length=32, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='supervise_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='督办人类型'),
        ),
        migrations.AlterField(
            model_name='ticketeventlog',
            name='processors_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='OPEN', max_length=32, verbose_name='处理人类型'),
        ),
        migrations.AlterField(
            model_name='ticketfield',
            name='type',
            field=models.CharField(choices=[('STRING', '单行文本'), ('TEXT', '多行文本'), ('INT', '数字'), ('DATE', '日期'), ('DATETIME', '日期时间'), ('DATETIMERANGE', '时间间隔'), ('TABLE', '表格'), ('SELECT', '单选下拉框'), ('INPUTSELECT', '可输入单选下拉框'), ('MULTISELECT', '多选下拉框'), ('CHECKBOX', '复选框'), ('RADIO', '单选框'), ('MEMBER', '单个人员选择'), ('MEMBERS', '多个人员选择'), ('RICHTEXT', '富文本'), ('FILE', '附件上传'), ('CUSTOMTABLE', '自定义表格'), ('TREESELECT', '树形选择'), ('LINK', '链接'), ('CUSTOM-FORM', '自定义表单'), ('CASCADE', '级联')], default='STRING', max_length=32, verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='ticketfollowernotifylog',
            name='followers_type',
            field=models.CharField(choices=[('CMDB', 'CMDB业务公用角色'), ('GENERAL', '通用角色表'), ('OPEN', '不限'), ('PERSON', '个人'), ('STARTER', '提单人'), ('STARTER_LEADER', '提单人上级'), ('ASSIGN_LEADER', '指定节点处理人上级'), ('BY_ASSIGNOR', '派单人指定'), ('EMPTY', '无'), ('ORGANIZATION', '组织架构'), ('VARIABLE', '引用变量'), ('VARIABLE_LEADER', '指定变量上级'), ('IAM', '权限中心角色')], default='EMPTY', max_length=32, verbose_name='处理者类型/角色类型'),
        ),
        migrations.AlterField(
            model_name='ticketremark',
            name='ticket_id',
            field=models.IntegerField(db_index=True, default=0, max_length=32, verbose_name='单据id'),
        ),
    ]
