# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-21 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_task', '0003_auto_20200212_1554'),
        ('periodic_task', '0004_auto_20191213_0828'),
    ]

    operations = [
    ]
